name: uno-vc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - scipy=1.13.1
  - h5py=3.14
  - matplotlib=3.9
  - jupyterlab
  - nbconvert
  - ipykernel
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torch==1.11.0+cu113
